# Generated by Django 4.2.1 on 2023-06-07 11:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("reporting_person_id", models.UUIDField()),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("absolute", "absolute"),
                            ("percentage", "percentage"),
                            ("euro/unit", "euro/unit"),
                        ],
                        default=None,
                        max_length=100,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "monthly"),
                            ("weekly", "weekly"),
                            ("daily", "daily"),
                        ],
                        default=None,
                        max_length=100,
                    ),
                ),
                (
                    "logic_level",
                    models.CharField(
                        choices=[
                            ("increased", "increased"),
                            ("decreased", "decreased"),
                        ],
                        default=None,
                        max_length=100,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPIs",
                "db_table": "kpi",
            },
        ),
        migrations.CreateModel(
            name="RelativeKPI",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relative_kpi_id", models.UUIDField()),
                ("absolute_kpi_id", models.UUIDField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("nominator", "nominator"),
                            ("denominator", "denominator"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "RelativeKPI",
                "verbose_name_plural": "RelativeKPIs",
                "db_table": "relativekpi",
            },
        ),
    ]
